baseURL      = "http://example.org/"
languageCode = "en-us"
title        = "oameed noakoasteen"
theme        = "oameed"

[params]
 user        = "Oameed Noakoasteen"
 LinkedIn    = "https://www.linkedin.com/in/oameed"
 Scholar     = "https://scholar.google.com/citations?user=XvXDLB8AAAAJ&hl=en"
 Orcid       = "https://orcid.org/0000-0001-6655-3378"
 GitLab      = "https://gitlab.com/oameed"
 GitHub      = "https://github.com/oameed"
 IEEE        = "https://ieeexplore.ieee.org/author/37088468432"
 RG          = "https://www.researchgate.net/profile/Oameed-Noakoasteen"
 SS          = "https://www.semanticscholar.org/author/Oameed-Noakoasteen/1904897405"
 AEDU        = "https://adamwohlwendart.academia.edu/oameednoakoasteen"
 PWC         = "https://paperswithcode.com/author/oameed-noakoasteen"
 DAI         = "https://deepai.org/profile/oameed"
 

