baseURL      = "http://example.org/"
languageCode = "en-us"
title        = "oameed noakoasteen"
theme        = "oameed"

[params]
 user        = "Oameed Noakoasteen"
 LinkedIn    = ""
 Scholar     = ""
 Orcid       = ""
 GitLab      = ""
 GitHub      = ""
 IEEE        = ""
 RG          = ""
 SS          = ""
 AEDU        = ""
 PWC         = ""
 DAI         = ""
 

